server:
    port: 8100
spring:
    application:
        name: crud_user
    datasource:
        url: jdbc:mysql://localhost:3306/crud_user
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: true
